doip-server: doip::MockServerTransport Class Reference
doip::MockServerTransport Class Reference
Mock server transport for testing.
#include <MockServerTransport.h>
Public Member Functions
MockServerTransport (const std::string &identifier="mock-server")
Construct a mock server transport.
~MockServerTransport () override=default
bool setup (uint16_t port) override
Set up the transport server (bind, listen)
std::unique_ptr< IConnectionTransport > acceptConnection () override
Accept a new incoming connection (blocking or with timeout)
ssize_t sendBroadcast (const DoIPMessage &msg, uint16_t port) override
Send a broadcast/announcement message (UDP)
void close () override
Close the server transport and cleanup resources.
bool isActive () const override
Check if the server transport is currently active.
std::string getIdentifier () const override
Get a human-readable identifier for this server transport.
void injectConnection (std::unique_ptr< MockConnectionTransport > connection)
Inject a mock connection that will be returned by acceptConnection()
std::optional< DoIPMessage > popBroadcast ()
Get the next broadcast message that was sent.
bool hasBroadcasts () const
Check if any broadcast messages have been sent.
size_t broadcastCount () const
Get the number of broadcast messages in the queue.
void clearQueues ()
Clear all queues (connections and broadcasts)
Public Member Functions inherited from doip::IServerTransport
virtual ~IServerTransport ()=default
Detailed Description
Mock server transport for testing.
Simulates a server transport without real sockets. Allows injecting connections and inspecting broadcasts.
Definition at line 20 of file MockServerTransport.h.
Constructor & Destructor Documentation
MockServerTransport()
doip::MockServerTransport::MockServerTransport (const std::string & identifier = "mock-server") explicit
Construct a mock server transport.
Parameters
identifier Descriptive name for logging
Definition at line 5 of file MockServerTransport.cpp.
~MockServerTransport()
doip::MockServerTransport::~MockServerTransport () override default
Member Function Documentation
acceptConnection()
std::unique_ptr< IConnectionTransport > doip::MockServerTransport::acceptConnection () override virtual
Accept a new incoming connection (blocking or with timeout)
For TCP: Calls accept() on server socket For Mock: Returns pre-injected mock connections
Returns
Unique pointer to connection transport, or nullptr if no connection available
Implements doip::IServerTransport.
Definition at line 15 of file MockServerTransport.cpp.
broadcastCount()
size_t doip::MockServerTransport::broadcastCount () const
Get the number of broadcast messages in the queue.
Returns
Number of broadcasts waiting to be read
Definition at line 69 of file MockServerTransport.cpp.
clearQueues()
void doip::MockServerTransport::clearQueues ()
Clear all queues (connections and broadcasts)
Definition at line 73 of file MockServerTransport.cpp.
Referenced by close().
close()
void doip::MockServerTransport::close () override virtual
Close the server transport and cleanup resources.
Closes all listening sockets and stops accepting connections
Implements doip::IServerTransport.
Definition at line 38 of file MockServerTransport.cpp.
References clearQueues().
getIdentifier()
std::string doip::MockServerTransport::getIdentifier () const override virtual
Get a human-readable identifier for this server transport.
Useful for logging (e.g., "TCP-Server:0.0.0.0:13400", "Mock-Server")
Returns
Server transport identifier string
Implements doip::IServerTransport.
Definition at line 47 of file MockServerTransport.cpp.
hasBroadcasts()
bool doip::MockServerTransport::hasBroadcasts () const
Check if any broadcast messages have been sent.
Returns
true if broadcast queue is not empty
Definition at line 65 of file MockServerTransport.cpp.
injectConnection()
void doip::MockServerTransport::injectConnection (std::unique_ptr< MockConnectionTransport > connection)
Inject a mock connection that will be returned by acceptConnection()
Parameters
connection The mock connection to inject
Definition at line 53 of file MockServerTransport.cpp.
isActive()
bool doip::MockServerTransport::isActive () const override virtual
Check if the server transport is currently active.
Returns
true if server is listening and can accept connections
Implements doip::IServerTransport.
Definition at line 43 of file MockServerTransport.cpp.
popBroadcast()
std::optional< DoIPMessage > doip::MockServerTransport::popBroadcast ()
Get the next broadcast message that was sent.
Returns
The broadcast message, or std::nullopt if queue is empty
Definition at line 57 of file MockServerTransport.cpp.
sendBroadcast()
ssize_t doip::MockServerTransport::sendBroadcast (const DoIPMessage & msg, uint16_t port) override virtual
Send a broadcast/announcement message (UDP)
For TCP: Sends UDP broadcast on port 13400 For Mock: Stores message for inspection
Parameters
msg The DoIP message to broadcast (typically vehicle announcement)
port The destination port for broadcast
Returns
Number of bytes sent, or -1 on error
Implements doip::IServerTransport.
Definition at line 28 of file MockServerTransport.cpp.
References doip::DoIPMessage::size().
setup()
bool doip::MockServerTransport::setup (uint16_t port) override virtual
Set up the transport server (bind, listen)
For TCP: Creates server socket, binds to port, starts listening For UDP: Creates UDP socket for announcements For Mock: No-op or in-memory setup
Parameters
port The port to bind to (e.g., 13400 for TCP)
Returns
true on success, false on error
Implements doip::IServerTransport.
Definition at line 9 of file MockServerTransport.cpp.
The documentation for this class was generated from the following files:
inc/tp/MockServerTransport.h
src/tp/MockServerTransport.cpp