doip-server: doip::TcpConnectionTransport Class Reference
doip::TcpConnectionTransport Class Reference
TCP connection transport for a single client.
#include <TcpConnectionTransport.h>
Public Member Functions
TcpConnectionTransport (int socket)
Construct a TCP connection transport from an existing socket.
~TcpConnectionTransport () override
Destructor - closes the socket.
TcpConnectionTransport (const TcpConnectionTransport &)=delete
TcpConnectionTransport & operator= (const TcpConnectionTransport &)=delete
ssize_t sendMessage (const DoIPMessage &msg) override
Send a DoIP message over this connection.
std::optional< DoIPMessage > receiveMessage () override
Receive a DoIP message from this connection.
void close (DoIPCloseReason reason) override
Close this connection.
bool isActive () const override
Check if this connection is currently active.
std::string getIdentifier () const override
Get a human-readable identifier for this connection.
Public Member Functions inherited from doip::IConnectionTransport
virtual ~IConnectionTransport ()=default
Detailed Description
TCP connection transport for a single client.
Wraps a connected TCP socket and provides DoIP message send/receive
Definition at line 18 of file TcpConnectionTransport.h.
Constructor & Destructor Documentation
TcpConnectionTransport() [1/2]
doip::TcpConnectionTransport::TcpConnectionTransport (int socket) explicit
Construct a TCP connection transport from an existing socket.
Parameters
socket The connected TCP socket (takes ownership)
Definition at line 12 of file TcpConnectionTransport.cpp.
~TcpConnectionTransport()
doip::TcpConnectionTransport::~TcpConnectionTransport () override
Destructor - closes the socket.
Definition at line 19 of file TcpConnectionTransport.cpp.
TcpConnectionTransport() [2/2]
doip::TcpConnectionTransport::TcpConnectionTransport (const TcpConnectionTransport &) delete
Member Function Documentation
close()
void doip::TcpConnectionTransport::close (DoIPCloseReason reason) override virtual
Close this connection.
Parameters
reason Why the connection is being closed
Implements doip::IConnectionTransport.
Definition at line 141 of file TcpConnectionTransport.cpp.
References fmt::streamed().
getIdentifier()
std::string doip::TcpConnectionTransport::getIdentifier () const override virtual
Get a human-readable identifier for this connection.
Useful for logging (e.g., "TCP:192.168.1.100:54321", "Mock-Client-1")
Returns
Connection identifier string
Implements doip::IConnectionTransport.
Definition at line 154 of file TcpConnectionTransport.cpp.
isActive()
bool doip::TcpConnectionTransport::isActive () const override virtual
Check if this connection is currently active.
Returns
true if the connection can send/receive, false otherwise
Implements doip::IConnectionTransport.
Definition at line 150 of file TcpConnectionTransport.cpp.
operator=()
TcpConnectionTransport& doip::TcpConnectionTransport::operator= (const TcpConnectionTransport &) delete
receiveMessage()
std::optional< DoIPMessage > doip::TcpConnectionTransport::receiveMessage () override virtual
Receive a DoIP message from this connection.
This method should block until a complete DoIP message is received or an error occurs.
Returns
The received DoIP message, or std::nullopt on error/disconnection
Implements doip::IConnectionTransport.
Definition at line 53 of file TcpConnectionTransport.cpp.
References doip::DOIP_HEADER_SIZE, fmt::streamed(), and doip::DoIPMessage::tryParseHeader().
sendMessage()
ssize_t doip::TcpConnectionTransport::sendMessage (const DoIPMessage & msg) override virtual
Send a DoIP message over this connection.
Parameters
msg The DoIP message to send
Returns
Number of bytes sent, or -1 on error
Implements doip::IConnectionTransport.
Definition at line 37 of file TcpConnectionTransport.cpp.
References doip::DoIPMessage::data(), and doip::DoIPMessage::size().
The documentation for this class was generated from the following files:
inc/tp/TcpConnectionTransport.h
src/tp/TcpConnectionTransport.cpp