doip-server: doip::DoIpVin Class Reference
doip::DoIpVin Class Reference
Vehicle Identification Number (VIN) - 17 bytes according to ISO 3779.
#include <DoIPIdentifiers.h>
Public Member Functions
DoIpVin ()
Default constructor - creates VIN filled with '0' padding.
DoIpVin (const std::string &vin)
Construct from string with automatic uppercase conversion.
DoIpVin (const char *vin)
Construct from C-style string with automatic uppercase conversion.
DoIpVin (const uint8_t *data, size_t length)
Construct from byte sequence (no validation, assumes pre-validated data)
DoIpVin (const ByteArray &byte_array)
Construct from ByteArray (no validation, assumes pre-validated data)
template<typename Integral , typename = std::enable_if_t<std::is_integral_v<Integral>>>
DoIpVin (Integral id_value)
Construct from integral value (for numeric VINs)
DoIpVin (const DoIpVin &)=default
DoIpVin & operator= (const DoIpVin &)=default
DoIpVin (DoIpVin &&) noexcept=default
DoIpVin & operator= (DoIpVin &&) noexcept=default
~DoIpVin ()=default
std::string toString () const
std::string toHexString () const
ByteArrayRef asByteArray () const
const std::array< uint8_t, 17 > & getArray () const
const uint8_t * data () const
ByteArray & appendTo (ByteArray &bytes) const
constexpr size_t size () const
bool isEmpty () const noexcept
bool operator== (const DoIpVin &other) const noexcept
bool operator!= (const DoIpVin &other) const noexcept
const uint8_t & operator[] (size_t index) const
constexpr char getPadChar () const noexcept
constexpr uint8_t getPadByte () const noexcept
auto begin () noexcept
auto begin () const noexcept
auto cbegin () const noexcept
auto end () noexcept
auto end () const noexcept
auto cend () const noexcept
bool isValid () const noexcept
Validate VIN according to ISO 3779 character set.
Static Public Attributes
static constexpr size_t VIN_LENGTH = 17
Length of VIN in bytes (ISO 3779)
static const DoIpVin Zero {}
Static zero-initialized VIN instance.
Detailed Description
Vehicle Identification Number (VIN) - 17 bytes according to ISO 3779.
This class enforces VIN validation rules:
Exactly 17 characters
Only uppercase alphanumeric characters (excluding I, O, Q)
Automatically converts lowercase to uppercase
Padded with ASCII '0' characters when shorter than 17 bytes
Definition at line 354 of file DoIPIdentifiers.h.
Constructor & Destructor Documentation
DoIpVin() [1/8]
doip::DoIpVin::DoIpVin () inline
Default constructor - creates VIN filled with '0' padding.
Definition at line 399 of file DoIPIdentifiers.h.
DoIpVin() [2/8]
doip::DoIpVin::DoIpVin (const std::string & vin) inline explicit
Construct from string with automatic uppercase conversion.
Parameters
vin VIN as string. Converted to uppercase and padded/truncated to 17 bytes. Does NOT validate character set to maintain backward compatibility. Use isValid() to check validity after construction.
Definition at line 408 of file DoIPIdentifiers.h.
DoIpVin() [3/8]
doip::DoIpVin::DoIpVin (const char * vin) inline explicit
Construct from C-style string with automatic uppercase conversion.
Parameters
vin VIN as C-string. Converted to uppercase and padded/truncated to 17 bytes. Does NOT validate character set to maintain backward compatibility. Use isValid() to check validity after construction.
Definition at line 418 of file DoIPIdentifiers.h.
DoIpVin() [4/8]
doip::DoIpVin::DoIpVin (const uint8_t * data, size_t length) inline
Construct from byte sequence (no validation, assumes pre-validated data)
Parameters
data Pointer to byte data
length Length of byte data
Definition at line 425 of file DoIPIdentifiers.h.
DoIpVin() [5/8]
doip::DoIpVin::DoIpVin (const ByteArray & byte_array) inline explicit
Construct from ByteArray (no validation, assumes pre-validated data)
Parameters
byte_array VIN as ByteArray
Definition at line 433 of file DoIPIdentifiers.h.
DoIpVin() [6/8]
template<typename Integral , typename = std::enable_if_t<std::is_integral_v<Integral>>> doip::DoIpVin::DoIpVin (Integral id_value) inline explicit
Construct from integral value (for numeric VINs)
Template Parameters
Integral Integral type
Parameters
id_value Numeric VIN value
Definition at line 444 of file DoIPIdentifiers.h.
DoIpVin() [7/8]
doip::DoIpVin::DoIpVin (const DoIpVin &) default
DoIpVin() [8/8]
doip::DoIpVin::DoIpVin (DoIpVin &&) default noexcept
~DoIpVin()
doip::DoIpVin::~DoIpVin () default
Member Function Documentation
appendTo()
ByteArray& doip::DoIpVin::appendTo (ByteArray & bytes) const inline
Definition at line 470 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::appendTo().
asByteArray()
ByteArrayRef doip::DoIpVin::asByteArray () const inline
Definition at line 461 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::asByteArray().
begin() [1/2]
auto doip::DoIpVin::begin () const inline noexcept
Definition at line 501 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::begin().
begin() [2/2]
auto doip::DoIpVin::begin () inline noexcept
Definition at line 498 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::begin().
Referenced by doip::message::makeVehicleIdentificationResponse().
cbegin()
auto doip::DoIpVin::cbegin () const inline noexcept
Definition at line 504 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::cbegin().
cend()
auto doip::DoIpVin::cend () const inline noexcept
Definition at line 513 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::cend().
data()
const uint8_t* doip::DoIpVin::data () const inline
Definition at line 467 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::data().
end() [1/2]
auto doip::DoIpVin::end () const inline noexcept
Definition at line 510 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::end().
end() [2/2]
auto doip::DoIpVin::end () inline noexcept
Definition at line 507 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::end().
Referenced by doip::message::makeVehicleIdentificationResponse().
getArray()
const std::array<uint8_t, 17>& doip::DoIpVin::getArray () const inline
Definition at line 464 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::getArray().
getPadByte()
constexpr uint8_t doip::DoIpVin::getPadByte () const inline constexpr noexcept
Definition at line 493 of file DoIPIdentifiers.h.
getPadChar()
constexpr char doip::DoIpVin::getPadChar () const inline constexpr noexcept
Definition at line 490 of file DoIPIdentifiers.h.
isEmpty()
bool doip::DoIpVin::isEmpty () const inline noexcept
Definition at line 476 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::isEmpty().
isValid()
bool doip::DoIpVin::isValid () const inline noexcept
Validate VIN according to ISO 3779 character set.
Returns
true if all characters are valid (A-Z except I,O,Q and 0-9)
Definition at line 522 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::begin(), and doip::GenericFixedId< IdLength, zeroPadding, padChar >::end().
operator!=()
bool doip::DoIpVin::operator!= (const DoIpVin & other) const inline noexcept
Definition at line 483 of file DoIPIdentifiers.h.
operator=() [1/2]
DoIpVin& doip::DoIpVin::operator= (const DoIpVin &) default
operator=() [2/2]
DoIpVin& doip::DoIpVin::operator= (DoIpVin &&) default noexcept
operator==()
bool doip::DoIpVin::operator== (const DoIpVin & other) const inline noexcept
Definition at line 480 of file DoIPIdentifiers.h.
operator[]()
const uint8_t& doip::DoIpVin::operator[] (size_t index) const inline
Definition at line 486 of file DoIPIdentifiers.h.
size()
constexpr size_t doip::DoIpVin::size () const inline constexpr
Definition at line 473 of file DoIPIdentifiers.h.
References VIN_LENGTH.
Referenced by doip::message::makeVehicleIdentificationResponse().
toHexString()
std::string doip::DoIpVin::toHexString () const inline
Definition at line 458 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::toHexString().
toString()
std::string doip::DoIpVin::toString () const inline
Definition at line 455 of file DoIPIdentifiers.h.
References doip::GenericFixedId< IdLength, zeroPadding, padChar >::toString().
Referenced by doip::operator<<().
Member Data Documentation
VIN_LENGTH
constexpr size_t doip::DoIpVin::VIN_LENGTH = 17 static constexpr
Length of VIN in bytes (ISO 3779)
Definition at line 391 of file DoIPIdentifiers.h.
Referenced by size().
Zero
const DoIpVin doip::DoIpVin::Zero {} inline static
Static zero-initialized VIN instance.
Definition at line 394 of file DoIPIdentifiers.h.
The documentation for this class was generated from the following file:
inc/DoIPIdentifiers.h