doip-server: doip::TcpServerTransport Class Reference
doip::TcpServerTransport Class Reference
TCP-based server transport implementation.
#include <TcpServerTransport.h>
Public Member Functions
TcpServerTransport (bool loopback=false)
Construct a TCP server transport.
~TcpServerTransport () override
Destructor - closes sockets.
TcpServerTransport (const TcpServerTransport &)=delete
TcpServerTransport & operator= (const TcpServerTransport &)=delete
bool setup (uint16_t port) override
Set up the transport server (bind, listen)
std::unique_ptr< IConnectionTransport > acceptConnection () override
Accept a new incoming connection (blocking or with timeout)
ssize_t sendBroadcast (const DoIPMessage &msg, uint16_t port) override
Send a broadcast/announcement message (UDP)
void close () override
Close the server transport and cleanup resources.
bool isActive () const override
Check if the server transport is currently active.
std::string getIdentifier () const override
Get a human-readable identifier for this server transport.
Public Member Functions inherited from doip::IServerTransport
virtual ~IServerTransport ()=default
Detailed Description
TCP-based server transport implementation.
Manages TCP server socket (listen/accept) and UDP socket (announcements)
Definition at line 17 of file TcpServerTransport.h.
Constructor & Destructor Documentation
TcpServerTransport() [1/2]
doip::TcpServerTransport::TcpServerTransport (bool loopback = false) explicit
Construct a TCP server transport.
Parameters
loopback If true, use loopback interface; otherwise use broadcast
Definition at line 13 of file TcpServerTransport.cpp.
~TcpServerTransport()
doip::TcpServerTransport::~TcpServerTransport () override
Destructor - closes sockets.
Definition at line 19 of file TcpServerTransport.cpp.
TcpServerTransport() [2/2]
doip::TcpServerTransport::TcpServerTransport (const TcpServerTransport &) delete
Member Function Documentation
acceptConnection()
std::unique_ptr< IConnectionTransport > doip::TcpServerTransport::acceptConnection () override virtual
Accept a new incoming connection (blocking or with timeout)
For TCP: Calls accept() on server socket For Mock: Returns pre-injected mock connections
Returns
Unique pointer to connection transport, or nullptr if no connection available
Implements doip::IServerTransport.
Definition at line 163 of file TcpServerTransport.cpp.
close()
void doip::TcpServerTransport::close () override virtual
Close the server transport and cleanup resources.
Closes all listening sockets and stops accepting connections
Implements doip::IServerTransport.
Definition at line 219 of file TcpServerTransport.cpp.
Referenced by setup().
getIdentifier()
std::string doip::TcpServerTransport::getIdentifier () const override virtual
Get a human-readable identifier for this server transport.
Useful for logging (e.g., "TCP-Server:0.0.0.0:13400", "Mock-Server")
Returns
Server transport identifier string
Implements doip::IServerTransport.
Definition at line 227 of file TcpServerTransport.cpp.
isActive()
bool doip::TcpServerTransport::isActive () const override virtual
Check if the server transport is currently active.
Returns
true if server is listening and can accept connections
Implements doip::IServerTransport.
Definition at line 223 of file TcpServerTransport.cpp.
operator=()
TcpServerTransport& doip::TcpServerTransport::operator= (const TcpServerTransport &) delete
sendBroadcast()
ssize_t doip::TcpServerTransport::sendBroadcast (const DoIPMessage & msg, uint16_t port) override virtual
Send a broadcast/announcement message (UDP)
For TCP: Sends UDP broadcast on port 13400 For Mock: Stores message for inspection
Parameters
msg The DoIP message to broadcast (typically vehicle announcement)
port The destination port for broadcast
Returns
Number of bytes sent, or -1 on error
Implements doip::IServerTransport.
Definition at line 190 of file TcpServerTransport.cpp.
References doip::DoIPMessage::data(), and doip::DoIPMessage::size().
setup()
bool doip::TcpServerTransport::setup (uint16_t port) override virtual
Set up the transport server (bind, listen)
For TCP: Creates server socket, binds to port, starts listening For UDP: Creates UDP socket for announcements For Mock: No-op or in-memory setup
Parameters
port The port to bind to (e.g., 13400 for TCP)
Returns
true on success, false on error
Implements doip::IServerTransport.
Definition at line 40 of file TcpServerTransport.cpp.
References close().
The documentation for this class was generated from the following files:
inc/tp/TcpServerTransport.h
src/tp/TcpServerTransport.cpp