doip-server: doip::TcpTransport Class Reference
doip::TcpTransport Class Reference
TCP-based transport implementation for DoIP.
#include <TcpTransport.h>
Public Member Functions
TcpTransport (int socket)
Construct a TCP transport from an existing socket.
~TcpTransport () override
Destructor - closes the socket.
TcpTransport (const TcpTransport &)=delete
TcpTransport & operator= (const TcpTransport &)=delete
ssize_t sendMessage (const DoIPMessage &msg) override
Send a DoIP message over the transport.
std::optional< DoIPMessage > receiveMessage () override
Receive a DoIP message from the transport.
void close (DoIPCloseReason reason) override
Close the transport connection.
bool isActive () const override
Check if the transport is currently active/connected.
std::string getIdentifier () const override
Get a human-readable identifier for this transport.
Public Member Functions inherited from doip::ITransport
virtual ~ITransport ()=default
Detailed Description
TCP-based transport implementation for DoIP.
Wraps a TCP socket and provides DoIP message send/receive functionality.
Definition at line 20 of file TcpTransport.h.
Constructor & Destructor Documentation
TcpTransport() [1/2]
doip::TcpTransport::TcpTransport (int socket) explicit
Construct a TCP transport from an existing socket.
Parameters
socket The connected TCP socket (takes ownership)
Definition at line 12 of file TcpTransport.cpp.
~TcpTransport()
doip::TcpTransport::~TcpTransport () override
Destructor - closes the socket.
Definition at line 19 of file TcpTransport.cpp.
References doip::ApplicationRequest, and close().
TcpTransport() [2/2]
doip::TcpTransport::TcpTransport (const TcpTransport &) delete
Member Function Documentation
close()
void doip::TcpTransport::close (DoIPCloseReason reason) override virtual
Close the transport connection.
Parameters
reason Reason for closing the transport After calling this, the transport is no longer usable.
Implements doip::ITransport.
Definition at line 139 of file TcpTransport.cpp.
References fmt::streamed().
Referenced by ~TcpTransport().
getIdentifier()
std::string doip::TcpTransport::getIdentifier () const override virtual
Get a human-readable identifier for this transport.
Useful for logging (e.g., "TCP:127.0.0.1:13400", "Mock")
Returns
Transport identifier string
Implements doip::ITransport.
Definition at line 152 of file TcpTransport.cpp.
isActive()
bool doip::TcpTransport::isActive () const override virtual
Check if the transport is currently active/connected.
Returns
true if the transport can send/receive, false otherwise
Implements doip::ITransport.
Definition at line 148 of file TcpTransport.cpp.
operator=()
TcpTransport& doip::TcpTransport::operator= (const TcpTransport &) delete
receiveMessage()
std::optional< DoIPMessage > doip::TcpTransport::receiveMessage () override virtual
Receive a DoIP message from the transport.
This method should block until a complete DoIP message is received or an error occurs.
Returns
The received DoIP message, or std::nullopt on error/disconnection
Implements doip::ITransport.
Definition at line 52 of file TcpTransport.cpp.
References doip::DOIP_HEADER_SIZE, fmt::streamed(), and doip::DoIPMessage::tryParseHeader().
sendMessage()
ssize_t doip::TcpTransport::sendMessage (const DoIPMessage & msg) override virtual
Send a DoIP message over the transport.
Parameters
msg The DoIP message to send
Returns
Number of bytes sent, or -1 on error
Implements doip::ITransport.
Definition at line 36 of file TcpTransport.cpp.
References doip::DoIPMessage::data(), and doip::DoIPMessage::size().
The documentation for this class was generated from the following files:
inc/tp/TcpTransport.h
src/tp/TcpTransport.cpp