doip-server: doip::Socket Class Reference
doip::Socket Class Reference
RAII wrapper for POSIX file descriptors (sockets)
#include <Socket.h>
Public Member Functions
Socket ()=default
Default constructor - creates invalid socket.
Socket (int fd)
Construct from existing file descriptor.
~Socket () noexcept
Destructor - automatically closes socket.
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
Socket (Socket &&other) noexcept
Move constructor.
Socket & operator= (Socket &&other) noexcept
Move assignment.
int get () const noexcept
Get the underlying file descriptor.
bool valid () const noexcept
Check if socket is valid.
int release () noexcept
Release ownership of the file descriptor.
void close () noexcept
Explicitly close the socket.
void reset (int fd=-1) noexcept
Reset to a new file descriptor.
operator bool () const noexcept
Implicit conversion to bool for validity checks.
Detailed Description
RAII wrapper for POSIX file descriptors (sockets)
Ensures sockets are properly closed when going out of scope, preventing resource leaks and improving exception safety.
Definition at line 15 of file Socket.h.
Constructor & Destructor Documentation
Socket() [1/4]
doip::Socket::Socket () default
Default constructor - creates invalid socket.
Socket() [2/4]
doip::Socket::Socket (int fd) inline explicit
Construct from existing file descriptor.
Parameters
fd File descriptor to wrap (takes ownership)
Definition at line 26 of file Socket.h.
~Socket()
doip::Socket::~Socket () inline noexcept
Destructor - automatically closes socket.
Definition at line 31 of file Socket.h.
References close().
Socket() [3/4]
doip::Socket::Socket (const Socket &) delete
Socket() [4/4]
doip::Socket::Socket (Socket && other) inline noexcept
Move constructor.
Definition at line 42 of file Socket.h.
Member Function Documentation
close()
void doip::Socket::close () inline noexcept
Explicitly close the socket.
Safe to call multiple times (idempotent). Automatically called by destructor.
Definition at line 93 of file Socket.h.
Referenced by operator=(), reset(), and ~Socket().
get()
int doip::Socket::get () const inline noexcept
Get the underlying file descriptor.
Returns
File descriptor, or -1 if invalid
Definition at line 63 of file Socket.h.
operator bool()
doip::Socket::operator bool () const inline explicit noexcept
Implicit conversion to bool for validity checks.
Definition at line 112 of file Socket.h.
References valid().
operator=() [1/2]
Socket& doip::Socket::operator= (const Socket &) delete
operator=() [2/2]
Socket& doip::Socket::operator= (Socket && other) inline noexcept
Move assignment.
Definition at line 49 of file Socket.h.
References close().
release()
int doip::Socket::release () inline noexcept
Release ownership of the file descriptor.
Returns
The file descriptor (caller must close it)
Definition at line 81 of file Socket.h.
reset()
void doip::Socket::reset (int fd = -1) inline noexcept
Reset to a new file descriptor.
Parameters
fd New file descriptor (takes ownership)
Definition at line 104 of file Socket.h.
References close().
valid()
bool doip::Socket::valid () const inline noexcept
Check if socket is valid.
Returns
true if socket is valid (fd >= 0)
Definition at line 72 of file Socket.h.
Referenced by operator bool().
The documentation for this class was generated from the following file:
inc/Socket.h